drop table if exists apartments CASCADE;
drop table if exists clients CASCADE;
drop table if exists contact CASCADE;
drop table if exists registration_cards CASCADE;
create table apartments
(
    id       bigint generated by default as identity (start with 1),
    booked   boolean,
    number   bigint not null,
    occupied boolean,
    primary key (id)
);
create table clients
(
    id          bigint generated by default as identity (start with 1),
    last_name   varchar(255) not null,
    name        varchar(255) not null,
    patronymic  varchar(255),
    contacts_id bigint,
    primary key (id)
);
create table contact
(
    id    bigint generated by default as identity (start with 1),
    email varchar(255) not null,
    phone varchar(255) not null,
    primary key (id)
);
create table registration_cards
(
    id              bigint generated by default as identity (start with 1),
    arrival         date,
    booked_date     timestamp,
    covid_test      boolean,
    leaving         date,
    paid            boolean,
    paid_date       timestamp,
    prepayment      boolean,
    prepayment_date timestamp,
    apartments_id   bigint,
    client_id       bigint,
    primary key (id)
);
alter table apartments
    add constraint UK_dmhhx9sfkla0skfd4pcoke9mv unique (number);
alter table contact
    add constraint UK_gnqwbwwcn7x0m5jlt4158dass unique (email);
alter table contact
    add constraint UK_n07fa8c8nqso88ftmqd0t50uh unique (phone);
alter table clients
    add constraint FKy0ubifnrh4idwviqrd4hqpfm foreign key (contacts_id) references contact;
alter table registration_cards
    add constraint FKo21wee9t9sej1akh9b6popgsh foreign key (apartments_id) references apartments;
alter table registration_cards
    add constraint FKonb6ro8bvarjd8i8hqhwfn9og foreign key (client_id) references clients;

insert into contact (id, email, phone)
values (default, 'sample@gmail.com', '211');
insert into clients (id, contacts_id, last_name, name, patronymic)
values (default, 1, 'Владислав', 'Игорь', 'Валерьевич');
insert into contact (id, email, phone)
values (default, 'sample@yandex.ru', '55');
insert into clients (id, contacts_id, last_name, name, patronymic)
values (default, 2, 'Игорь', 'Олег', 'Владиславовыч');
insert into contact (id, email, phone)
values (default, 'sample@yahoo.com', '8800');
insert into clients (id, contacts_id, last_name, name, patronymic)
values (default, 3, 'Олег', 'Клиент', 'Игоревич');
insert into apartments (id, booked, number, occupied)
values (default, true, 1, false);
insert into apartments (id, booked, number, occupied)
values (default, false, 2, false);
insert into apartments (id, booked, number, occupied)
values (default, true, 3, true);
insert into registration_cards (id, apartments_id, arrival, booked_date, client_id, covid_test, leaving, paid,
                                paid_date, prepayment, prepayment_date)
values (default, 1, '2022-03-11', '2022-03-11 00:56:21.314572', 1, false, '2022-03-12', false, null, false, null);
insert into registration_cards (id, apartments_id, arrival, booked_date, client_id, covid_test, leaving, paid,
                                paid_date, prepayment, prepayment_date)
values (default, 2, '2022-03-10', '2022-03-12 01:56:21.314572', 2, false, '2022-03-15', false, null, false, null);
insert into registration_cards (id, apartments_id, arrival, booked_date, client_id, covid_test, leaving, paid,
                                paid_date, prepayment, prepayment_date)
values (default, 3, '2022-03-12', '2022-03-12 01:56:21.314572', 3, false, '2022-03-15', false, null, false, null);